FROM python:3.14-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*


RUN pip install "pix2tex[api]"

RUN python -c "from pix2tex.cli import LatexOCR; LatexOCR()"

EXPOSE 8502

CMD ["uvicorn", "pix2tex.api.app:app", "--host", "0.0.0.0", "--port", "8502"]